# Elenco dei server da monitorare.
# host: IP o hostname da pingare
# port: (opzionale) porta TCP da verificare in aggiunta al ping
servers:
  - name: nuc1
    host: nuc1.station
    port: 443

  - name: nuc2
    host: nuc2.station
    port: 8006

  - name: nuc3
    host: nuc3.station
    port: 443
